// data/products.js

const products = [
  {
    id: 1,
    name: "کاپشن مردانه زمستانی",
    description: "کاپشن گرم و ضد آب مناسب فصل زمستان",
    color: "مشکی",
    material: "پلی‌استر",
    price: 1850000,
    image: "/images/jacket1.webp",
    category: "کاپشن",
    off: "20%",
  },
  {
    id: 2,
    name: "هودی کلاه‌دار",
    description: "هودی اسپرت و راحت برای استفاده روزمره",
    color: "خاکستری",
    material: "پنبه",
    price: 850000,
    image: "/images/jacket2.webp",
    category: "هودی",
    off: "10%",
  },
  {
    id: 3,
    name: "شال گردن بافتنی",
    description: "شال گردن دست‌بافت نرم و گرم",
    color: "آبی",
    material: "پشم",
    price: 320000,
    image: "/images/scarf1.webp",
    category: "شال گردن",
  },
  {
    id: 4,
    name: "کاپشن یقه گرد",
    description: "کاپشن ساده و کلاسیک مناسب مهمانی و روزمره",
    color: "زرشکی",
    material: "پنبه و اکریلیک",
    price: 690000,
    image: "/images/scarf2.webp",
    category: "کاپشن",
  },
  {
    id: 5,
    name: "کت جین مردانه",
    description: "کت جین خوش‌دوخت با طراحی مدرن",
    color: "آبی نفتی",
    material: "جین",
    price: 980000,
    image: "/images/jacket3.webp",
    category: "کت",
  },
  {
    id: 6,
    name: "کاپشن زنانه کوتاه",
    description: "کاپشن سبک و شیک مناسب پاییز",
    color: "سبز زیتونی",
    material: "پلی‌استر",
    price: 1450000,
    image: "/images/jacket2.weWbp",
    category: "کاپشن",
    off: "10%",
  },
  {
    id: 7,
    name: "هودی اورسایز",
    description: "هودی آزاد و راحت برای استایل خیابانی",
    color: "بنفش",
    material: "پنبه",
    price: 920000,
    image: "/images/hoodie2.webp",
    category: "هودی",
    off: "40%",
  },
  {
    id: 8,
    name: "شال گردن طرح دار",
    description: "شال گردن با طرح هندسی مدرن",
    color: "مشکی-سفید",
    material: "اکریلیک",
    price: 280000,
    image: "/images/scarf2.webp",
    category: "شال گردن",
  },
  {
    id: 9,
    name: "کاپشن یقه اسکی",
    description: "کاپشن گرم و شیک مناسب زمستان",
    color: "کرم",
    material: "پشم",
    price: 770000,
    image: "/images/sweater2.webp",
    category: "کاپشن",
    off: "20%",
  },
  {
    id: 10,
    name: "کت چرم مردانه",
    description: "کت چرم مصنوعی شیک و مقاوم",
    color: "مشکی",
    material: "چرم مصنوعی",
    price: 2100000,
    image: "/images/leatherjacket1.webp",
    category: "کت",
    off: "25%",
  },
  {
    id: 11,
    name: "کاپشن بلند زنانه",
    description: "کاپشن بلند و گرم با کلاه خزدار",
    color: "قرمز",
    material: "پلی‌استر",
    price: 1950000,
    image: "/images/jacket3.webp",
    category: "کاپشن",
  },
  {
    id: 12,
    name: "هودی ساده",
    description: "هودی سبک و راحت مناسب ورزش و روزمره",
    color: "سفید",
    material: "پنبه",
    price: 780000,
    image: "/images/hoodie3.webp",
    category: "هودی",
  },
  {
    id: 13,
    name: "شال گردن پشمی",
    description: "شال گردن گرم و ضخیم برای روزهای سرد",
    color: "خاکی",
    material: "پشم",
    price: 350000,
    image: "/images/scarf3.webp",
    category: "شال گردن",
  },
  {
    id: 14,
    name: "کاپشن راه‌راه",
    description: "کاپشن سبک با طرح راه‌راه رنگی",
    color: "آبی-سفید",
    material: "پنبه",
    price: 650000,
    image: "/images/sweater3.webp",
    category: "کاپشن",
  },
  {
    id: 15,
    name: "کت رسمی مردانه",
    description: "کت رسمی مناسب محیط کاری و مهمانی",
    color: "سرمه‌ای",
    material: "پلی‌استر-ویسکوز",
    price: 1750000,
    image: "/images/blazer1.webp",
    category: "کت",
  },

  {
    id: 16,
    name: "بوت مردانه چرمی",
    description: "بوت مردانه با طراحی مدرن و مقاوم برای استفاده روزمره",
    color: "مشکی",
    material: "چرم طبیعی",
    price: 1950000,
    image: "/images/boot1.webp",
    category: "بوت و نیم‌بوت",
  },
  {
    id: 17,
    name: "هودی مردانه اسپرت",
    description: "هودی راحت و سبک مناسب استفاده روزمره و ورزش",
    color: "خاکستری",
    material: "پنبه و پلی‌استر",
    price: 850000,
    image: "/images/hoodie1.webp",
    category: "هودی",
  },
  {
    id: 18,
    name: "هودی زنانه کلاه‌دار",
    description: "هودی شیک و نرم با کلاه بزرگ برای پاییز و زمستان",
    color: "صورتی",
    material: "پنبه و پلی‌استر",
    price: 920000,
    image: "/images/hoodie2.webp",
    category: "هودی",
  },
];

export default products;
